gastos/urls.py
from django.urls import path

from . import  views

app_name = 'gastos'

urlpatterns = [
    path('', views.gasto_list, name='list'),
    path('<int:gasto_id>/', views.gasto_detail, name='detail'),
    path('nuevo/', views.gasto_create, name='new'),
    path('editar/<int:gasto_id>/', views.gasto_update, name='update'),
    path('delete/<int:gasto_id>/', views.gasto_delete, name='delete'),
]

inversiones/urls.py
from django.urls import path

from . import  views

app_name = 'inversiones'

urlpatterns = [
    path('', views.inversion_list, name='list'),
    path('<int:inversion_id>/', views.inversion_detail, name='detail'),
    path('nuevo/', views.inversion_create, name='new'),
    path('editar/<int:inversion_id>/', views.inversion_update, name='update'),
    path('delete/<int:inversion_id>/', views.inversion_delete, name='delete'),
]

servicell/urls.py
from django.contrib import admin
from django.urls import path, include
from almacenes import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),  ##pagina principal
    path('almacen/', include('almacenes.urls')),
    path('inversion/', include('inversiones.urls')),
    path('gasto/', include('gastos.urls')),
    path('utilidad/', include('utilidades.urls')),
]

inversiones/models.py
from django.db import models
from almacenes.models import Almacen


class Inversion(models.Model):
    descripcion = models.CharField(max_length=200)
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    almacen_id = models.ForeignKey(Almacen, on_delete=models.CASCADE)

    def __str__(self):
        return self.descripcion

inversiones/forms.py
from django.forms import ModelForm

from .models import Inversion

class InversionForm(ModelForm):
    class Meta:
        model = Inversion
        fields = '__all__'

inversiones/views.py
from django.shortcuts import render,redirect

from .models import Inversion
from .forms import InversionForm



def inversion_list(request):
    """vista de la lista de inversiones"""

    inversion_list = Inversion.objects.all()
    context = {'inversion_list': inversion_list}
    return render(request, 'inversiones/inversion_list.html', context)


def inversion_detail(request, inversion_id):
    """vista de inversion detail"""

    inversion = Inversion.objects.get(id=inversion_id)
    context = {'inversion':inversion}
    return render(request,'inversiones/inversion_detail.html', context)


def inversion_create(request):
    """vista para crear un nuevo resgistro de inversion"""

    if request.method == 'POST':
        form = InversionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/inversion/')
    else:
        form = InversionForm()
    return render(request, 'inversiones/inversion_form.html', {'form':form})


def inversion_update(request, inversion_id):
    inversion = Inversion.objects.get(id=inversion_id)
    if request.method == 'POST':
        form = InversionForm(request.POST, instance=inversion)
        if form.is_valid():
            form.save()
            return redirect('/inversion/')
    else:
        form = InversionForm(instance=inversion)
    return render(request, 'inversiones/inversion_form.html', {'form':form})



def inversion_delete(request, inversion_id):
    """vista para eliminar un registro de inversion"""

    inversion = Inversion.objects.get(id=inversion_id)
    inversion.delete()
    return redirect('/inversion/')

templates/inversiones/inversion_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>Inversion No.{{inversion.id}}</h1>
    <h2>Descripcion: {{inversion.descripcion}}</h2>
    <h2>Valor: {{inversion.valor}}</h2>

    
    <a href="{% url 'inversiones:list'%}">Lista de Inversiones</a>
    <a href="{% url 'inversiones:update' inversion.id%}">Editar Registro</a>
    <a href="{% url 'inversiones:delete' inversion.id%}">Eliminar Registro</a>
{% endblock %}

templates/inversiones/inversion_form.html
{% extends 'base.html' %}

{%block content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form }}
    </table>
    <input type="submit" value="Submit" />
</form>
{% endblock %}

templates/inversiones/inversion_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Lista de Inversiones</h1>
    <a href="{% url 'inversiones:new' %}">Agregar</a>
    {% for inversion in inversion_list %}
        <li><a href="{% url 'inversiones:detail' inversion.id %}">{{inversion.id}}</a> - {{inversion.descripcion}} - {{inversion.valor}}</li>
    {% endfor %}
{% endblock %}