gastos/urls.py
from django.urls import path

from . import  views

app_name = 'gastos'

urlpatterns = [
    path('', views.gasto_list, name='list'),
    path('<int:gasto_id>/', views.gasto_detail, name='detail'),
    path('nuevo/', views.gasto_create, name='new'),
    path('editar/<int:gasto_id>/', views.gasto_update, name='update'),
    path('delete/<int:gasto_id>/', views.gasto_delete, name='delete'),
]

servicell/urls.py
from django.contrib import admin
from django.urls import path, include
from almacenes import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),  ##pagina principal
    path('almacen/', include('almacenes.urls')),
    path('inversion/', include('inversiones.urls')),
    path('gasto/', include('gastos.urls')),
    path('utilidad/', include('utilidades.urls')),
]

utilidades/urls.py
from django.urls import path

from . import  views

app_name = 'utilidades'

urlpatterns = [
    path('', views.utilidad_list, name='list'),
    path('<int:utilidad_id>/', views.utilidad_detail, name='detail'),
    path('nuevo/', views.utilidad_create, name='new'),
    path('editar/<int:utilidad_id>/', views.utilidad_update, name='update'),
    path('delete/<int:utilidad_id>/', views.utilidad_delete, name='delete'),
]

utilidades/models.py
from django.db import models

from almacenes.models import Almacen

class Utilidad(models.Model):
    descripcion = models.CharField(max_length=200)
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    almacen_id = models.ForeignKey(Almacen, on_delete=models.CASCADE)

    def __str__(self):
        return self.descripcion

utilidades/forms.py
from django.forms import ModelForm

from .models import Utilidad


class UtilidadForm(ModelForm):
    class Meta:
        model = Utilidad
        fields = '__all__'

utilidades/views.py
from django.shortcuts import render,redirect

from .models import Utilidad
from .forms import UtilidadForm




def utilidad_list(request):
    """vista de la lista de utilidades"""

    utilidad_list = Utilidad.objects.all()
    context = {'utilidad_list': utilidad_list}
    return render(request, 'utilidades/utilidad_list.html', context)


def utilidad_detail(request, utilidad_id):
    """vista de utilidad detail"""

    utilidad = Utilidad.objects.get(id=utilidad_id)
    context = {'utilidad':utilidad}
    return render(request,'utilidades/utilidad_detail.html', context)


def utilidad_create(request):
    """vista para crear un nuevo resgistro de utilidad"""

    if request.method == 'POST':
        form = UtilidadForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/utilidad/')
    else:
        form = UtilidadForm()
    return render(request, 'utilidades/utilidad_form.html', {'form':form})


def utilidad_update(request, utilidad_id):
    utilidad = Utilidad.objects.get(id=utilidad_id)
    if request.method == 'POST':
        form = UtilidadForm(request.POST, instance=utilidad)
        if form.is_valid():
            form.save()
            return redirect('/utilidad/')
    else:
        form = UtilidadForm(instance=utilidad)
    return render(request, 'utilidades/utilidad_form.html', {'form':form})



def utilidad_delete(request, utilidad_id):
    """vista para eliminar un registro de utilidad"""

    utilidad = Utilidad.objects.get(id=utilidad_id)
    utilidad.delete()
    return redirect('/utilidad/')

templates/utilidades/utilidad_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>Utilidad No.{{utilidad.id}}</h1>
    <h2>Descripcion: {{utilidad.descripcion}}</h2>
    <h2>Valor: {{utilidad.valor}}</h2>

    
    <a href="{% url 'utilidades:list'%}">Lista de Utilidades</a>
    <a href="{% url 'utilidades:update' utilidad.id%}">Editar Registro</a>
    <a href="{% url 'utilidades:delete' utilidad.id%}">Eliminar Registro</a>
{% endblock %}

templates/utilidades/utilidad_form.html
{% extends 'base.html' %}

{%block content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form }}
    </table>
    <input type="submit" value="Submit" />
</form>
{% endblock %}

templates/utilidades/utilidad_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Lista de Utilidades</h1>
    <a href="{% url 'utilidades:new' %}">Agregar</a>
    {% for utilidad in utilidad_list %}
        <li><a href="{% url 'utilidades:detail' utilidad.id %}">{{utilidad.id}}</a> - {{utilidad.descripcion}} - {{utilidad.valor}}</li>
    {% endfor %}
{% endblock %}