gastos/urls.py
from django.urls import path

from . import  views

app_name = 'gastos'

urlpatterns = [
    path('', views.gasto_list, name='list'),
    path('<int:gasto_id>/', views.gasto_detail, name='detail'),
    path('nuevo/', views.gasto_create, name='new'),
    path('editar/<int:gasto_id>/', views.gasto_update, name='update'),
    path('delete/<int:gasto_id>/', views.gasto_delete, name='delete'),
]

servicell/urls.py
from django.contrib import admin
from django.urls import path, include
from almacenes import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),  ##pagina principal
    path('almacen/', include('almacenes.urls')),
    path('inversion/', include('inversiones.urls')),
    path('gasto/', include('gastos.urls')),
    path('utilidad/', include('utilidades.urls')),
]

gastos/models.py
from django.db import models

from almacenes.models import Almacen


class Tipo_Gasto(models.Model):
    nombre = models.CharField(max_length=200)

    def __str__(self):
        return self.nombre

class Gasto(models.Model):
    gasto_id = models.ForeignKey(Tipo_Gasto, on_delete=models.CASCADE)
    descripcion = models.CharField(max_length=200)
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    almacen_id = models.ForeignKey(Almacen, on_delete=models.CASCADE)

    def __str__(self):
        return self.gasto_id.nombre

gastos/forms.py
from django.forms import ModelForm

from .models import Gasto, Tipo_Gasto


class Tipo_GastoForm(ModelForm):
    class Meta:
        model = Tipo_Gasto
        fields = '__all__'


class GastoForm(ModelForm):
    class Meta:
        model = Gasto
        fields = '__all__'

gastos/views.py
from django.shortcuts import render,redirect

from .models import Gasto, Tipo_Gasto
from .forms import GastoForm, Tipo_GastoForm



def gasto_list(request):
    """vista de la lista de gastos"""

    gasto_list = Gasto.objects.all()
    context = {'gasto_list': gasto_list}
    return render(request, 'gastos/gasto_list.html', context)


def gasto_detail(request, gasto_id):
    """vista de gasto detail"""

    gasto = Gasto.objects.get(id=gasto_id)
    context = {'gasto':gasto}
    return render(request,'gastos/gasto_detail.html', context)


def gasto_create(request):
    """vista para crear un nuevo resgistro de gasto"""

    if request.method == 'POST':
        form = GastoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/gasto/')
    else:
        form = GastoForm()
    return render(request, 'gastos/gasto_form.html', {'form':form})


def gasto_update(request, gasto_id):
    gasto = Gasto.objects.get(id=gasto_id)
    if request.method == 'POST':
        form = GastoForm(request.POST, instance=gasto)
        if form.is_valid():
            form.save()
            return redirect('/gasto/')
    else:
        form = GastoForm(instance=gasto)
    return render(request, 'gastos/gasto_form.html', {'form':form})



def gasto_delete(request, gasto_id):
    """vista para eliminar un registro de gasto"""

    gasto = Gasto.objects.get(id=gasto_id)
    gasto.delete()
    return redirect('/gasto/')

templates/gastos/gasto_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>Gasto No.{{gasto.id}}</h1>
    <h2>Tipo de gasto: {{gasto.gasto_id}}</h2>
    <h2>Descripcion: {{gasto.descripcion}}</h2>
    <h2>Valor: {{gasto.valor}}</h2>

    
    <a href="{% url 'gastos:list'%}">Lista de Gastos</a>
    <a href="{% url 'gastos:update' gasto.id%}">Editar Registro</a>
    <a href="{% url 'gastos:delete' gasto.id%}">Eliminar Registro</a>
{% endblock %}

templates/gastos/gasto_form.html
{% extends 'base.html' %}

{%block content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form }}
    </table>
    <input type="submit" value="Submit" />
</form>
{% endblock %}

templates/gastos/gasto_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Lista de Gastos</h1>
    <a href="{% url 'gastos:new' %}">Agregar</a>
    {% for gasto in gasto_list %}
        <li><a href="{% url 'gastos:detail' gasto.id %}">{{gasto.id}}</a> - {{gasto.gasto_id}} - {{gasto.descripcion}} - {{gasto.valor}}</li>
    {% endfor %}
{% endblock %}